
export default {
  ADD_PRODUCT: "ADD_PRODUCT",
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_MESSAGE: "SET_MESSAGE",
  DELETE_PRODUCT: "DELETE_PRODUCT",
};
